### ISSUE TITLE
Expand on Chroma subsampling

### ISSUE THREAD

**Issue by chittti** [leandromoreira/digital_video_introduction#24]
In the Chrome subsampling part, it wasn't specified what the individual numbers exactly mean. In the 4:2:0 example, why were the Cb and Cr occupying only horizontal half of what the Y part was covering? Specifically, what do the 4, 2 and 0 even mean? 

Including the slide 48 from the linked Google Sheets would maybe help understand everything better. [This website](http://www.red.com/learn/red-101/video-chroma-subsampling) goes into much more (maybe too much) detail, so maybe link as a side note in case people don't immediately understand?

**Comment by Waranoi** [comment]
I don't fully understand the Chroma subsampling ratios so I went online to find more info but that just ended with me becoming more confused. [This](http://blogs.adobe.com/VideoRoad/2010/06/color_subsampling_or_what_is_4.html) blog post shows an example of 4:2:0 subsampling which seemingly conflicts with the statement given in this introduction 

> *y* is the number of changes of chroma samples between the first and seconds rows of a pixels.

I assume that if the number of sample changes between the first and second and row (i.e. y) is 0 then the chroma subsampling of row one and two should be identical, which is not the case in the mentioned blog post.

All that aside, the only reason I started looking up other resources was because I found it hard to understand the explanation of the different ratios. Maybe having an example image similar to the _YCbCr 4:2:0 merge_ but for 4:2:2 would illustrate what the *y* value does. I personally found the illustration from the blog post more intuitive.

My current understanding of the subsampling system presented in this introduction might be completely wrong, I can't come up with any suggestions for improvement in that case.

**Comment by Waranoi** [comment]
Indeed, after looking it up I also think that the visualization from Wikipedia is clearer. Having multiple example images and _J_, _a_ and _b_ indexes to the side makes it a lot easier for me to understand. Also your expanded explanation of the _b_ index helps a lot.

So if I understand correctly, the 2 in 4:2:0 does _not_ mean that it only uses chrominance values found in the first row, because the 0 in 4:2:0 says that the final colour for row 1 and row 2 are identical. That's why both row 1 and row 2 can be used to sample the final color? If it's like this then I would understand why the article and this intro's explanation are not conflicting each other.

**Comment by matteocontrini** [comment]
>That's why both row 1 and row 2 can be used to sample the final color?

Yes. As you say, in 4:2:0 the final chrominance is identical for row 1 and row 2, so you can spread the chrominance information (Cb and Cr) in which row you want, and then use row 1 and/or row 2 at your choice to revert the subsampling

**Comment by Waranoi** [comment]
Nice! If it's ok for you I might create a pull request later with the stuff you told me because I think it's much easier to understand than the current subsampling section.

**Comment by matteocontrini** [comment]
Of course :)
